### ISSUE TITLE
Cannot download Hunspell dictionaries

### ISSUE THREAD

**Issue by Erysipelothrix** [Predelnik/DSpellCheck#229]
Installed Notepad 7.9 and DSpell. When trying to Download language dictionaries, the program hangs up. I posted it to the Notepad ++ Blog but was advised to go to this forum. Is there a remedy or another source for the Hunspell files?
A progression bar shows up for less than a second and Windows shows info that Notepad++ does not function any more.

Thank you in advance

**Comment by Predelnik** [comment]
Are you sure you are using latest version? If not can you try the latest please:
https://github.com/Predelnik/DSpellCheck/releases/tag/v1.4.17

Also it would be extremely helpful if you would send me crash dump when program crashed which could be obtained through Task Manager like this:
![image](https://user-images.githubusercontent.com/2133957/95500036-dfe1aa80-09ae-11eb-8005-5d28fb81879e.png)

**Comment by Predelnik** [comment]
Also I slightly improved diagnostics in not yet released 1.4.18, please also check it out if you can:

https://github.com/Predelnik/DSpellCheck/releases/tag/v1.4.18

I cannot reproduce your problem that easily and fix it without your assistance unfortunately.

**Comment by Erysipelothrix** [comment]
You got the link to the Dump File?. (I resent the Email just now) The version 1.4.18 did not change the behavior. If there is another source for the hunspell files, I only need En(US) and German (Germany) momentarily.

**Comment by Predelnik** [comment]
@Erysipelothrix Sorry, unfortunately do not see it in my e-mail, make sure that you're sending to predelnik@gmail.com 

As for dictionaries, it's not that hard to get them since plugin also downloads them from the public github repo https://github.com/LibreOffice/dictionaries , it could be done manually. But I want to say that resolving this crash is very important for me and I would really glad to receive a dump file from you in any case.

**Comment by Erysipelothrix** [comment]
please check you Email for the dump file

**Comment by Predelnik** [comment]
1.4.18 should fix the crash which was happening if any problem during download occurred unfortunately, I plan to implement displaying more detailed errors in the next version

**Comment by qbert220** [comment]
I had the same problem as OP with version 1.4.17. I updated to version 1.4.18, and I no longer see a crash, but instead a dialog box saying "Sadly no dictionaries were copied. Please try again". Trying again doesn't help though.

**Comment by ballios** [comment]
Notepad++ v7.9 (64-bit)
Unfortunately, version DSpellCheck 1.4.18 does not solve the problem of downloading dictionaries!
This time, when I try to download the dictionaries, I get a notification:
- Dictionaries Haven't Been Downloaded
- Sadly, no Dictionaries were copied, please try again

**Comment by Predelnik** [comment]
@ballios it solves the problem that it doesn't crash first and foremost. Further on I will add an error description but it is not guaranteed to be 100% helpful. The problem is most likely related to your system configuration as it works in some (hopefully most of the) cases.

**Comment by Predelnik** [comment]
All right, looks like I've made terrible typo during 1.4.17 release, sorry for not diagnosing it sooner. Anyway, probably going to release 1.4.19 with the fix in a matter of days.

**Comment by VvladimirvV** [comment]
> All right, looks like I've made terrible typo during 1.4.17 release, sorry for not diagnosing it sooner. Anyway, probably going to release 1.4.19 with the fix in a matter of days.

Thanks, waiting new version

**Comment by pryrt** [comment]
In my experiments as a result of https://community.notepad-plus-plus.org/topic/20250/download-dictionaries-dialog, v1.4.19 correctly fixes the download bug.

**Comment by Predelnik** [comment]
Should be fixed in 1.4.19:
https://github.com/Predelnik/DSpellCheck/releases/tag/v1.4.19
